trigger: none

pool:
  vmImage: ubuntu-latest

steps:

- checkout: self
  fetchDepth: 0

- task: UseNode@1
  inputs:
    version: '20.x'
  displayName: 'Install Node.js'

- script: |
    echo "registry=https://pkgs.dev.azure.com/rmpablos/botas/_packaging/botas-dev/npm/registry/" > .npmrc
    echo "always-auth=true" >> .npmrc
    echo "@rido-min:registry=https://pkgs.dev.azure.com/rmpablos/botas/_packaging/botas-dev/npm/registry/" >> .npmrc
    echo "always-auth=true" >> .npmrc
  displayName: 'Create .npmrc for azddevops' 

- task: npmAuthenticate@0
  inputs:
    workingFile: .npmrc

- task: Npm@1
  inputs:
    command: install
    customRegistry: useFeed
    customFeed : botas/botas-upstream
    verbose: true
  displayName: 'npm install'

- script: npm run build
  displayName: 'npm build'

- script: node setVersion.js
  displayName: 'node setVersion.js'

- task: Npm@1
  inputs:
    command: custom
    customCommand: publish --workspaces
    publishRegistry: useFeed
    publishFeed : botas/botas-dev
    verbose: true
  displayName: 'npm publish'

