#!/usr/bin/env node
// Syncs the version from package.json into src/version.ts for Deno/JSR compatibility.
import { readFileSync, writeFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const pkgPath = resolve(__dirname, '..', 'package.json')
const versionPath = resolve(__dirname, '..', 'src', 'version.ts')

const { version } = JSON.parse(readFileSync(pkgPath, 'utf8'))

const content = `// This file is auto-generated by scripts/sync-version.mjs — do not edit manually.
export const VERSION = '${version}'
`

writeFileSync(versionPath, content)
console.log(`Synced version ${version} to src/version.ts`)
